-- Create Profiles Table
create table public.profiles (
  id uuid references auth.users not null primary key,
  full_name text,
  avatar_url text,
  role text default 'customer' check (role in ('customer', 'admin')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Categories
create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Products
create table public.products (
  id bigint generated by default as identity primary key,
  category_id bigint references public.categories,
  name text not null,
  description text,
  price numeric not null,
  stock integer default 0,
  images text[],
  size text,
  stock_status text default 'In Stock',
  is_featured boolean default false,
  is_seasonal boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- (Orders table definition remains here, no changes needed yet) 
create table public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles,
  total_amount numeric not null,
  status text default 'pending' check (status in ('pending', 'processing', 'shipped', 'delivered', 'cancelled')),
  payment_status text default 'unpaid',
  shipping_address jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Coupons
create table public.coupons (
  id bigint generated by default as identity primary key,
  code text not null unique,
  discount_type text default 'percentage' check (discount_type in ('percentage', 'fixed')),
  discount_value numeric not null,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Order Items
create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders on delete cascade,
  product_id bigint references public.products,
  quantity integer not null,
  price numeric not null
);

-- Create Addresses
create table public.addresses (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles not null,
  full_name text not null,
  phone text not null,
  address_line1 text not null,
  address_line2 text,
  city text not null,
  state text not null,
  postal_code text not null,
  is_default boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Reviews
create table public.reviews (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products on delete cascade,
  user_id uuid references public.profiles,
  rating integer check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- OTP Verifications Table
create table public.otp_verifications (
  id uuid primary key default gen_random_uuid(),
  identifier text not null,
  type text not null check (type in ('phone', 'email')),
  code text not null,
  expires_at timestamp with time zone not null,
  verified boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index idx_otp_identifier on public.otp_verifications(identifier, verified, expires_at);

-- Verification Tokens (for verified OTPs before password is set)
create table public.verification_tokens (
  id uuid primary key default gen_random_uuid(),
  identifier text not null,
  token text not null unique,
  purpose text not null check (purpose in ('signup', 'reset')),
  expires_at timestamp with time zone not null,
  used boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index idx_verification_token on public.verification_tokens(token, used, expires_at);

-- Security
alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.addresses enable row level security;
alter table public.reviews enable row level security;
alter table public.otp_verifications enable row level security;
alter table public.verification_tokens enable row level security;

-- Policies
create policy "Public profiles are viewable by everyone." on public.profiles for select using (true);
create policy "Users can update their own profile." on public.profiles for update using (auth.uid() = id);

create policy "Categories are viewable by everyone." on public.categories for select using (true);
create policy "Products are viewable by everyone." on public.products for select using (true);

create policy "Users can view their own orders." on public.orders for select using (auth.uid() = user_id);
create policy "Users can view their own order items." on public.order_items for select using (
  exists (
    select 1 from public.orders
    where public.orders.id = public.order_items.order_id
    and public.orders.user_id = auth.uid()
  )
);

create policy "Users can manage their own addresses." on public.addresses for all using (auth.uid() = user_id);

create policy "Reviews are viewable by everyone." on public.reviews for select using (true);
create policy "Authenticated users can create reviews." on public.reviews for insert with check (auth.role() = 'authenticated');
