-- Create offers table
CREATE TABLE IF NOT EXISTS public.offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    coupon_code TEXT NOT NULL,
    image_url TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.offers ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read access for offers" 
ON public.offers FOR SELECT 
TO public 
USING (is_active = true);

-- Allow admin full access
CREATE POLICY "Allow admin all access for offers" 
ON public.offers FOR ALL 
TO authenticated 
USING (
    EXISTS (
        SELECT 1 FROM public.admin_users 
        WHERE email = auth.email()
    )
);

-- Function to update updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger for updated_at
CREATE TRIGGER update_offers_updated_at
BEFORE UPDATE ON public.offers
FOR EACH ROW
EXECUTE PROCEDURE update_updated_at_column();
