-- Create Bulk Enquiries Table
create table public.bulk_enquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  email text,
  phone text not null,
  quantity text,
  message text,
  status text default 'new' check (status in ('new', 'contacted', 'resolved')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Corporate Enquiries Table
create table public.corporate_enquiries (
  id bigint generated by default as identity primary key,
  company_name text not null,
  contact_person text not null,
  email text,
  phone text not null,
  requirements text,
  status text default 'new' check (status in ('new', 'in-progress', 'completed')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table public.bulk_enquiries enable row level security;
alter table public.corporate_enquiries enable row level security;

-- Admin can view/edit, Users can insert
create policy "Admins can view all bulk enquiries" on public.bulk_enquiries for select using (auth.role() = 'authenticated'); -- Simplified for now, or check profile role
create policy "Anyone can insert bulk enquiries" on public.bulk_enquiries for insert with check (true);

create policy "Admins can view all corporate enquiries" on public.corporate_enquiries for select using (auth.role() = 'authenticated');
create policy "Anyone can insert corporate enquiries" on public.corporate_enquiries for insert with check (true);
