create table public.shipping_rates (
  id bigint generated by default as identity primary key,
  state_name text not null unique,
  charge numeric not null default 150,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS
alter table public.shipping_rates enable row level security;

create policy "Shipping rates are viewable by everyone." 
on public.shipping_rates for select using (true);

create policy "Admins can insert shipping rates." 
on public.shipping_rates for insert with check (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

create policy "Admins can update shipping rates." 
on public.shipping_rates for update using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

create policy "Admins can delete shipping rates." 
on public.shipping_rates for delete using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

-- Seed Data
INSERT INTO public.shipping_rates (state_name, charge) VALUES
('Andhra Pradesh', 150),
('Arunachal Pradesh', 150),
('Assam', 150),
('Bihar', 150),
('Chhattisgarh', 150),
('Goa', 150),
('Gujarat', 150),
('Haryana', 150),
('Himachal Pradesh', 150),
('Jharkhand', 150),
('Karnataka', 150),
('Kerala', 100),
('Madhya Pradesh', 150),
('Maharashtra', 150),
('Manipur', 150),
('Meghalaya', 150),
('Mizoram', 150),
('Nagaland', 150),
('Odisha', 150),
('Punjab', 150),
('Rajasthan', 150),
('Sikkim', 150),
('Tamil Nadu', 50),
('Telangana', 150),
('Tripura', 150),
('Uttar Pradesh', 150),
('Uttarakhand', 150),
('West Bengal', 150),
('Andaman and Nicobar Islands', 200),
('Chandigarh', 150),
('Dadra and Nagar Haveli and Daman and Diu', 150),
('Delhi', 150),
('Jammu and Kashmir', 150),
('Ladakh', 150),
('Lakshadweep', 200),
('Puducherry', 150)
ON CONFLICT (state_name) DO NOTHING;
